name: Test in Docker
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v**'

defaults:
  run:
    shell: bash

jobs:
  container-test-job:
    name: Container Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/baconpaul/sst-dockerimages/ubuntu18_surge_build:main
    steps:
      - name: uname-a
        run: |
          uname -a
          ls -l
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 11
          cmake --version
