name: Test in Docker
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v**'

defaults:
  run:
    shell: bash

jobs:
  container-test-job:
    name: Container Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/baconpaul/sst-dockerimages/ubuntu18_surge_build:main
    steps:
      - name: uname-a
        run: |
          uname -a
          ls -l
          cmake --version
          gcc --version
